from __future__ import annotations

import json
from dataclasses import asdict
from pathlib import Path

from .model import AnalysisResult


FIELD_LABELS = {
    "issuer": "Issuer",
    "rating": "Rating",
    "industry": "Industry",
    "ownership": "Ownership",
    "revenue": "Revenue",
    "ebitda": "EBITDA",
    "total_debt": "Total debt",
    "short_term_debt": "Short-term debt",
    "cash": "Cash",
    "operating_cash_flow": "Operating cash flow",
    "capital_expenditure": "Capital expenditure",
    "interest_expense": "Interest expense",
}


def format_field_value(value: object, unit: str | None) -> str:
    if isinstance(value, float):
        rendered = f"{value:.2f}".rstrip("0").rstrip(".")
    else:
        rendered = str(value)
    return f"{rendered} {unit}" if unit else rendered


def render_markdown(result: AnalysisResult) -> str:
    issuer = result.fields.get("issuer")
    issuer_name = issuer.value if issuer else "Unknown issuer"
    lines: list[str] = [
        f"# Credit Analysis Memo: {issuer_name}",
        "",
        f"Source: `{result.source_path}`",
        "",
        "## Extracted Facts",
        "",
        "| Field | Value | Source line |",
        "|---|---:|---:|",
    ]

    for name in FIELD_LABELS:
        field = result.fields.get(name)
        if field:
            lines.append(f"| {FIELD_LABELS[name]} | {format_field_value(field.value, field.unit)} | {field.source_line or ''} |")

    lines.extend(["", "## Credit Metrics", "", "| Metric | Value | Formula |", "|---|---:|---|"])
    for metric in result.metrics.values():
        lines.append(f"| {metric.name} | {metric.value:.2f} {metric.unit} | {metric.formula} |")

    lines.extend(["", "## Risk Flags", ""])
    if not result.risks:
        lines.append("No material baseline risk flags were detected.")
    else:
        for risk in result.risks:
            citation = f" Source lines: {', '.join(map(str, risk.source_lines))}." if risk.source_lines else ""
            lines.append(f"- **{risk.severity.upper()} / {risk.category}:** {risk.message}{citation}")

    lines.extend(["", "## Analyst Questions", ""])
    for question in result.analyst_questions:
        lines.append(f"- {question}")

    lines.extend(
        [
            "",
            "## Method Note",
            "",
            "This memo was generated by a deterministic baseline. Future versions should compare LLM/RAG outputs against this baseline for accuracy, citation quality, and risk coverage.",
            "",
        ]
    )
    return "\n".join(lines)


def write_markdown(result: AnalysisResult, path: str | Path) -> None:
    target = Path(path)
    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text(render_markdown(result), encoding="utf-8")


def write_json(result: AnalysisResult, path: str | Path) -> None:
    target = Path(path)
    target.parent.mkdir(parents=True, exist_ok=True)
    payload = asdict(result)
    target.write_text(json.dumps(payload, ensure_ascii=False, indent=2), encoding="utf-8")

